/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#05070d",
        "secondary-fixed-dim": "#97a3b8",
        "surface-container-lowest": "#05070d",
        "secondary-fixed": "#c0cfe0",
        "outline-variant": "rgba(150, 178, 220, 0.25)",
        "surface-container-high": "#131b2a",
        "inverse-surface": "#e6edf7",
        "primary-fixed": "#65f0ff",
        "on-tertiary-fixed": "#2e1500",
        "surface-container": "#0d1320",
        "on-secondary-fixed-variant": "#31495f",
        "on-tertiary-container": "#ffcea9",
        "tertiary": "#ffb84d",
        "on-tertiary": "#2e1500",
        "on-surface-variant": "#97a3b8",
        "tertiary-container": "#6b3a00",
        "secondary-container": "#0d1f30",
        "inverse-primary": "#004a77",
        "surface": "#080b14",
        "inverse-on-surface": "#1c2026",
        "primary-container": "#003d4d",
        "surface-bright": "#1a2436",
        "background": "#080b14",
        "on-secondary": "#e6edf7",
        "surface-dim": "#05070d",
        "tertiary-fixed-dim": "#ffb84d",
        "on-surface": "#e6edf7",
        "on-secondary-container": "#97a3b8",
        "tertiary-fixed": "#ffdcc2",
        "surface-container-highest": "#1e2a3a",
        "on-error": "#690005",
        "primary": "#00e5ff",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#0c111c",
        "error": "#ff3d71",
        "on-tertiary-fixed-variant": "#6d3900",
        "primary-fixed-dim": "#00bcd4",
        "secondary": "#97a3b8",
        "on-secondary-fixed": "#021d32",
        "surface-variant": "#131b2a",
        "error-container": "#93000a",
        "outline": "rgba(150, 178, 220, 0.4)",
        "on-primary-fixed": "#05070d",
        "surface-tint": "#00e5ff",
        "on-primary-container": "#65f0ff",
        "on-primary-fixed-variant": "#004a77",
        "on-background": "#e6edf7"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["JetBrains Mono", "ui-monospace", "monospace"],
        "mono": ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      borderRadius: {
        "DEFAULT": "0px",
        "sm": "2px",
        "lg": "4px",
        "xl": "8px",
        "2xl": "12px",
        "3xl": "16px",
        "full": "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
