/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#003354",
        "secondary-fixed-dim": "#b1c9e4",
        "surface-container-lowest": "#0a0e14",
        "secondary-fixed": "#cee5ff",
        "outline-variant": "#414750",
        "surface-container-high": "#262a31",
        "inverse-surface": "#dfe2eb",
        "primary-fixed": "#cee5ff",
        "on-tertiary-fixed": "#2e1500",
        "surface-container": "#1c2026",
        "on-secondary-fixed-variant": "#31495f",
        "on-tertiary-container": "#ffcea9",
        "tertiary": "#ffb77b",
        "on-tertiary": "#4d2700",
        "on-surface-variant": "#c0c7d1",
        "tertiary-container": "#8f4d00",
        "secondary-container": "#344b62",
        "inverse-primary": "#02639c",
        "surface": "#10141a",
        "inverse-on-surface": "#2d3137",
        "primary-container": "#00629b",
        "surface-bright": "#353940",
        "background": "#10141a",
        "on-secondary": "#1a3248",
        "surface-dim": "#10141a",
        "tertiary-fixed-dim": "#ffb77b",
        "on-surface": "#dfe2eb",
        "on-secondary-container": "#a3bbd6",
        "tertiary-fixed": "#ffdcc2",
        "surface-container-highest": "#31353c",
        "on-error": "#690005",
        "primary": "#98cbff",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#181c22",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#6d3900",
        "primary-fixed-dim": "#98cbff",
        "secondary": "#b1c9e4",
        "on-secondary-fixed": "#021d32",
        "surface-variant": "#31353c",
        "error-container": "#93000a",
        "outline": "#8a919b",
        "on-primary-fixed": "#001d33",
        "surface-tint": "#98cbff",
        "on-primary-container": "#badbff",
        "on-primary-fixed-variant": "#004a77",
        "on-background": "#dfe2eb"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
